### ISSUE TITLE
look into detecting cases and give a more helpful error message

### ISSUE THREAD

**Issue by Fl4m3thrower** [Tillerino/Tillerinobot#221]
Reference LAUFNJ

**Comment by omkelderman** [comment]
Thanks Flame for putting this here :D, now that im not half asleep anymore, time to add a bit of context:

someone on discord reported `!u` not working with the following error message:
![image](https://user-images.githubusercontent.com/2544736/211496713-a7182da0-5726-4490-af92-45dd67a9106f.png)

osu!track website at the same time:
![image](https://user-images.githubusercontent.com/2544736/211496778-18e8128a-ea94-4736-8772-5482a2f27ca5.png)

Ameo bot:
![image](https://user-images.githubusercontent.com/2544736/211496826-81ec4876-13c4-4781-9334-ab4aa6d6ebc0.png)

meaning that the actual problem was somewhere on osutrack servers. But our error message did not reflect that at all, so we should look into the osutrack api call and its handling and figure out if there is anything in the response that indicates this kind of thing is happening and give an actual helpful response message like Ameo bot is doing.

@Tillerino In the stacktrace I see an jakarta.ws.rs.InternalServerErrorException which would make sense in this case, a 500 error is what I would expect. I guess its probably as simple as adding a new catch block to https://github.com/Tillerino/Tillerinobot/blob/master/tillerinobot/src/main/java/tillerino/tillerinobot/handlers/OsuTrackHandler.java#L65 with that InternalServerErrorException? Do we want to do that, or do we want to catch *all* 5xx errors, and if yes, how?

**Comment by Tillerino** [comment]
Exactly. You can catch a `ServerErrorException` if you want to catch all 5xx.
