### ISSUE TITLE
shit

### ISSUE THREAD

**Issue by OfficialArctic** [Tillerino/Tillerinobot#62]
m8 this is fucking shit fix it k

**Comment by TheHowl** [comment]
Thank you for your bug report!

As it currently stands, though, your bug report is inappropriate. Please reformulate the title and the description of this issue, in order to make it easier for us to troubleshoot what exactly is your problem, both the one related with Tillerinobot and the one you apparently have <sup>in <sup>your <sup>brain</sup></sup></sup>.

Have a wonderful day!

**Comment by sup** [comment]
I do have to agree with my fellow colleague. Unfortunately, the content that you state to have an issue with is not only rather rude towards the developers, but also to everyone around you. If I were you, I would consider reevaluating my actions and thinking about how I appeal to human beings around me. However, this is only a suggestion, but still, please refrain from filing bug reports with such vile language.

**Comment by OfficialArctic** [comment]
That's offensive, I have autism.

**Comment by OfficialArctic** [comment]
how about you kill yourself

**Comment by sup** [comment]
I wouldn't consider that an appropriate course of action.

**Comment by OfficialArctic** [comment]
k then gtfo and go to http://pornhub.com

**Comment by omkelderman** [comment]
> That's offensive, I have autism.

How on earth are those two related??

Also there is atm only one person offensive, and thats you @OfficialArctic

**Comment by OfficialArctic** [comment]
LOL THIS IS SO FUNNY

**Comment by OfficialArctic** [comment]
http://gloryholefoundation.com

**Comment by sup** [comment]
The only one this appears to be 'funny' for is you, as a matter of fact.

**Comment by Tillerino** [comment]
Thank you for your input.
